"""
harness_disjoint.py — revised harness (Generated by Haskell Orchestrator).

Two changes vs. the original harness.py, both enforcing conditions the paper
claims:

  H3 (independence): the harness loads ONLY this hypothesis's pre-assigned,
      disjoint validation split (wine_validation_H{k}.csv), never a shared file.

  H1 (uniform nulls): the statistical test is a paired sign-flip permutation
      test on INDEPENDENT held-out per-example losses (verified_stats), not a
      paired t-test on overlapping CV folds. The harness — not the LLM — fits
      the models and computes the per-example losses, so the test is fully
      harness-controlled and its null calibration is guaranteed.

The optimize()/get_baseline() artifacts supplied by the LLM are model builders
(unfitted estimators); the harness fits them on the split's training rows and
evaluates per-example on the held-out rows. The validation split is never
visible to optimize() (OS-level mount namespace, sandbox.py), so this fitting
happens only in the harness's own validation phase.
"""

from __future__ import annotations

import os
import sys

import numpy as np
import pandas as pd
from sklearn.base import clone
from sklearn.model_selection import train_test_split

from verified_stats import paired_permutation_pvalue

DATA_DIR = os.environ.get("DATA_DIR", "data")


def _split_path(hyp_id: int) -> str:
    return os.path.join(DATA_DIR, f"wine_validation_H{hyp_id}.csv")


def per_example_losses(builder, X_tr, y_tr, X_te, y_te) -> np.ndarray:
    """Fit a fresh model and return per-example 0/1 loss on the held-out rows."""
    model = clone(builder)
    model.fit(X_tr, y_tr)
    pred = model.predict(X_te)
    return (pred != y_te).astype(float)


def run_validation(hyp_id: int, optimized_builder, baseline_builder,
                   seed: int = 7) -> float:
    """Harness-controlled validation for one hypothesis on its disjoint split."""
    path = _split_path(hyp_id)
    if not os.path.exists(path):
        print(f"Assigned validation split missing: {path}")
        sys.exit(1)
    data = pd.read_csv(path)
    X = data.drop("target", axis=1).values
    y = data["target"].values

    # Split the hypothesis's own disjoint block into train / held-out test.
    # The held-out examples are independent units for the permutation test.
    X_tr, X_te, y_tr, y_te = train_test_split(
        X, y, test_size=0.5, random_state=seed, stratify=y)

    loss_opt = per_example_losses(optimized_builder, X_tr, y_tr, X_te, y_te)
    loss_base = per_example_losses(baseline_builder, X_tr, y_tr, X_te, y_te)

    p_value = paired_permutation_pvalue(
        loss_opt, loss_base, alternative="a_better",
        rng=np.random.default_rng(seed))
    return p_value


# ---- default LLM-supplied artifacts (stub for a runnable demonstration) ----
def _default_baseline():
    from sklearn.svm import SVC
    return SVC(C=0.01, kernel="linear", random_state=0)


def _default_optimized():
    from sklearn.pipeline import make_pipeline
    from sklearn.preprocessing import StandardScaler
    from sklearn.svm import SVC
    return make_pipeline(StandardScaler(), SVC(C=1.0, kernel="rbf",
                                               random_state=0))


if __name__ == "__main__":
    hyp_id = int(sys.argv[1]) if len(sys.argv) > 1 else 1
    p = run_validation(hyp_id, _default_optimized(), _default_baseline())
    print(f"H{hyp_id}: held-out paired permutation p-value = {p:.4f}")
    print(f"FINAL_P_VALUE:{p}")
