# harness.py (Generated by Haskell Orchestrator)
import implementation
import pandas as pd
import numpy as np
import sys, os

HYP_ID = 4  # this hypothesis's disjoint validation split (H3)

# === Locate the data directory portably (walk up from this file) ===
def _find_data_dir():
    d = os.path.dirname(os.path.abspath(__file__))
    for _ in range(6):
        cand = os.path.join(d, "data")
        if os.path.exists(os.path.join(cand, "wine_exploration.csv")):
            return cand
        d = os.path.dirname(d)
    print("Error: data/ with wine_exploration.csv not found"); sys.exit(1)

DATA_DIR = _find_data_dir()
EXPLORATION_DATA_PATH = os.path.join(DATA_DIR, "wine_exploration.csv")
VALIDATION_DATA_PATH = os.path.join(DATA_DIR, f"wine_validation_H{HYP_ID}.csv")

def load_data(path):
    try:
        return pd.read_csv(path)
    except FileNotFoundError as e:
        print(f"Error loading data: {e}. Check path: {path}"); sys.exit(1)

# === Statistical test: paired sign-flip permutation on held-out
# === per-example losses (super-uniform nulls, H1) ===
N_PERM = 20000
from sklearn.base import clone

def _per_example_loss(model, X, y):
    return (model.predict(X) != y).astype(float)

def permutation_pvalue(optimized, baseline, expl, val, seed=0):
    # optimized is already fit on exploration; fit a fresh baseline on the same data.
    Xe, ye = expl.drop('target', axis=1).values, expl['target'].values
    Xv, yv = val.drop('target', axis=1).values, val['target'].values
    # Fit fresh clones of both on exploration (robust whether or not
    # optimize() already returned a fitted estimator).
    opt = clone(optimized); opt.fit(Xe, ye)
    base = clone(baseline); base.fit(Xe, ye)
    loss_opt = _per_example_loss(opt, Xv, yv)
    loss_base = _per_example_loss(base, Xv, yv)
    d = loss_base - loss_opt            # > 0 favors the optimized model
    n = d.shape[0]; obs = float(d.sum())
    if n == 0:
        return 1.0
    rng = np.random.default_rng(seed)
    if n <= 22:                          # exact enumeration of sign flips
        idx = np.arange(1 << n)
        signs = ((idx[:, None] >> np.arange(n)) & 1).astype(float) * 2.0 - 1.0
        return float(np.mean(signs @ d >= obs - 1e-12))
    count, drawn = 0, 0                  # Monte-Carlo with +1/+1 correction
    while drawn < N_PERM:
        b = min(4096, N_PERM - drawn)
        flips = rng.integers(0, 2, size=(b, n)).astype(float) * 2.0 - 1.0
        count += int(np.sum(flips @ d >= obs - 1e-12))
        drawn += b
    return float((count + 1) / (N_PERM + 1))

# === Execution Phases ===
def run_exploration():
    print("--- Harness: Running Exploration Phase ---")
    data = load_data(EXPLORATION_DATA_PATH)
    # Only exploration data is passed to the LLM-generated code.
    artifact = implementation.optimize(data.copy())
    return artifact

def run_validation(optimized, baseline):
    print(f"--- Harness: Validation on disjoint split H{HYP_ID} ---")
    expl = load_data(EXPLORATION_DATA_PATH)
    val = load_data(VALIDATION_DATA_PATH)
    return permutation_pvalue(optimized, baseline, expl, val)

# === Main Execution Flow: Exploration -> Validation ===
if __name__ == "__main__":
    baseline_artifact = implementation.get_baseline()
    optimized_artifact = run_exploration()
    p_value = run_validation(optimized_artifact, baseline_artifact)
    print(f"FINAL_P_VALUE:{p_value}")
